# -*- coding: utf-8 -*-
"""crawler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nzzOvm2pvwipHmSGon6TjLYq4O3EDb9j

# COVID-19 Tracker 
A web crawler with Python to obtain COVID-19 data from the Worldometers Website. Build as part of the course [Python Programming Basics](https://ilearningx.huawei.com/courses/course-v1:HuaweiX+EBG2020NCHW1100108+Self-paced/about) by Huawei.
 * Worldometers has a credible sources of COVID19 data.
 * Dataset: https://www.worldometers.info/coronavirus/
"""

# import required libraries
import requests as req
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

"""## 1. Get data"""

# request data from website
html = req.get("https://www.worldometers.info/coronavirus/")

# check downloaded content
html.content

"""## 2. Parse html"""

# parse html with BeautifulSoup
html_parsed = BeautifulSoup(html.content)

# search for the required table
table = html_parsed.find('table', attrs={'id': 'main_table_countries_today'})

# check result
table

# get all the rows
rows = table.find_all("tr")

# check result
rows[0]

# scrap the text content
rows[0].text.strip()

# tokenization
rows[9].text.strip().split('\n')

"""## 3. Store data"""

# store rows in to list
data = []
for x in rows:
  data.append(x.text.strip().split('\n')[1:5])

# convert data (list) to DataFrame
df = pd.DataFrame(data)

# check DataFrame
df.head()

# set the first row as the header
df = pd.DataFrame(data[9:], columns=data[0])

# check the change
df.head()

# save as csv
df.to_csv('covid19.csv')

"""## 4. Visualize"""

# get the required columns
df_plot = df[['Country,Other', 'TotalCases']]

# get the first 10 rows
df_plot = df_plot[:10]

# check the DataFrame
df_plot.head()

# remove commas in digits and convert string to int
df_plot['TotalCases'] = df_plot['TotalCases'].apply(lambda x: x.replace(',', '')).astype(int)

# check the change
df_plot.head()

# plot
df_plot.plot(kind='bar', x='Country,Other', y='TotalCases')